# Stage 1: Build Vue
FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm install vue-router@4 vite-plugin-vuetify axios @mdi/font
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
