services:
  db:
    image: postgres:13
    container_name: robotdoc-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: robotdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/robotdb.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: robotdoc-backend
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_pass@db:5432/robotdb
      - APP_SCRT_KEY=dev_secret_key
     # - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    #deploy:
     # resources:
     #   reservations:
      #    devices:
       #     - capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: robotdoc-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
