services:
  db:
    image: postgres:13
    container_name: robotdoc-db
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/robotdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - robodoc-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: robotdoc-backend
    environment:
      - DATABASE_URL
      - APP_SCRT_KEY
      - PYTHONDONTWRITEBYTECODE=1
      - CORS_ORIGINS
    ports:
      - "5000:5000"
    depends_on:
      - db
      - llama
    volumes:
      - ./backend:/app
      - pip_cache:/root/.cache/pip
      - llava_imgs:/app/modules/img
    networks:
      - robodoc-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: robotdoc-frontend
    env_file: .env
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - robodoc-net

  llama:
    build:
      context: ./llama
      dockerfile: Dockerfile
    container_name: robotdoc-llama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "65143:65143"
    volumes:
      - ./llama:/app
      - pip_cache:/root/.cache/pip
      - hf_cache:/root/.cache/huggingface
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - robodoc-net

  llava:
    build:
      context: ./llava
      dockerfile: Dockerfile
    container_name: robotdoc-llava
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "65533:65533"
    volumes:
      - ./llava:/app
      - pip_cache:/root/.cache/pip
      - hf_cache:/root/.cache/huggingface
      - llava_imgs:/app/img
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - robodoc-net
volumes:
  pgdata:
  pip_cache:
  hf_cache:
  llava_imgs:

networks:
  robodoc-net:
