services:
  db:
    image: postgres:13
    container_name: robotdoc-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: robotdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./robotdb.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: robotdoc-app
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_pass@db:5432/robotdb
      - APP_SCRT_KEY=dev_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
