FROM python:3.8-slim
RUN apt-get update && apt-get install -y python3-dev libpq-dev gcc musl-dev

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /app


EXPOSE 5000
CMD [ "flask","--app","app.py","run","-h","0.0.0.0"]
