FROM python:3.8-slim
RUN apt-get update; exit 0 && apt-get install -y python3-dev libpq-dev gcc musl-dev ; exit 0

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app


EXPOSE 5000
CMD [ "flask","--app","app.py","run","-h","0.0.0.0"]
