# syntax=docker/dockerfile:1.4
FROM robotdoc-llama-base

ENV PYTHONUNBUFFERED=1

WORKDIR /app


EXPOSE 65143


CMD ["sh", "-c", "tail -f /dev/null"]
#CMD ["sh", "-c", "python setup_robodoc_direct.py || tail -f /dev/null"]
